userConfig:
  server: 1
  name: 测试工具
  account: testaccount
  password: testpassword
deduceConfig:
  overEntry: 不灭
  type: 内功
  entrys:
    - entry: 攻击
      level: 50
    - entry: 防御
      level: 50
    - entry: 命中
      level: 50
    - entry: 招架
      level: 50
accessories:
  food: true
  fy: true
  xlu: true
