userConfig:
  server: 1
  name: 测试工具
  account: testaccount
  password: testpassword
deduceConfig:
  overEntry: 不灭
  type: 内功
  entrys:
    攻击: 50
    防御: 50
    命中: 50
    招架: 50
    不灭: 0
accessories:
  food: true
  fy: true
  xlu: true
